# Generated by Django 3.1.5 on 2021-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
