# Generated by Django 3.1.5 on 2021-01-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210127_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_in']},
        ),
        migrations.AddField(
            model_name='event',
            name='bin',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
